# Generated by Django 5.0.4 on 2024-05-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialPlanningTools', '0002_alter_savingsgoal_current_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
